# vim:ft=ansible:
---
# tasks file for spike.common
- name: Update System
  apt: update_cache=yes
  environment:
    http_proxy: http://proxy.rd.francetelecom.fr:8080


- name: Upgrade System
  apt: upgrade=yes
  environment: 
    http_proxy: http://proxy.rd.francetelecom.fr:8080
